// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.1
// source: blog/v1/article.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 保存文章
type ReqSaveArticle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid    int32    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Detail *Article `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
}

func (x *ReqSaveArticle) Reset() {
	*x = ReqSaveArticle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_v1_article_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSaveArticle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSaveArticle) ProtoMessage() {}

func (x *ReqSaveArticle) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_article_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSaveArticle.ProtoReflect.Descriptor instead.
func (*ReqSaveArticle) Descriptor() ([]byte, []int) {
	return file_blog_v1_article_proto_rawDescGZIP(), []int{0}
}

func (x *ReqSaveArticle) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ReqSaveArticle) GetDetail() *Article {
	if x != nil {
		return x.Detail
	}
	return nil
}

type RespSaveArticle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode int32 `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
}

func (x *RespSaveArticle) Reset() {
	*x = RespSaveArticle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_v1_article_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespSaveArticle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespSaveArticle) ProtoMessage() {}

func (x *RespSaveArticle) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_article_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespSaveArticle.ProtoReflect.Descriptor instead.
func (*RespSaveArticle) Descriptor() ([]byte, []int) {
	return file_blog_v1_article_proto_rawDescGZIP(), []int{1}
}

func (x *RespSaveArticle) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

// 删除文章
type ReqDeleteArticle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid       int32 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ArticleId int32 `protobuf:"varint,2,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
}

func (x *ReqDeleteArticle) Reset() {
	*x = ReqDeleteArticle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_v1_article_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqDeleteArticle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqDeleteArticle) ProtoMessage() {}

func (x *ReqDeleteArticle) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_article_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqDeleteArticle.ProtoReflect.Descriptor instead.
func (*ReqDeleteArticle) Descriptor() ([]byte, []int) {
	return file_blog_v1_article_proto_rawDescGZIP(), []int{2}
}

func (x *ReqDeleteArticle) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ReqDeleteArticle) GetArticleId() int32 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

type RespDeleteArticle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode int32 `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
}

func (x *RespDeleteArticle) Reset() {
	*x = RespDeleteArticle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_v1_article_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespDeleteArticle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespDeleteArticle) ProtoMessage() {}

func (x *RespDeleteArticle) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_article_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespDeleteArticle.ProtoReflect.Descriptor instead.
func (*RespDeleteArticle) Descriptor() ([]byte, []int) {
	return file_blog_v1_article_proto_rawDescGZIP(), []int{3}
}

func (x *RespDeleteArticle) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

// 请求文章
type ReqArticleDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid       int32 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ArticleId int32 `protobuf:"varint,2,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
}

func (x *ReqArticleDetail) Reset() {
	*x = ReqArticleDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_v1_article_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqArticleDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqArticleDetail) ProtoMessage() {}

func (x *ReqArticleDetail) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_article_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqArticleDetail.ProtoReflect.Descriptor instead.
func (*ReqArticleDetail) Descriptor() ([]byte, []int) {
	return file_blog_v1_article_proto_rawDescGZIP(), []int{4}
}

func (x *ReqArticleDetail) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ReqArticleDetail) GetArticleId() int32 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

type RespArticleDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Detail *Article `protobuf:"bytes,1,opt,name=detail,proto3" json:"detail,omitempty"`
}

func (x *RespArticleDetail) Reset() {
	*x = RespArticleDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_v1_article_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespArticleDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespArticleDetail) ProtoMessage() {}

func (x *RespArticleDetail) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_article_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespArticleDetail.ProtoReflect.Descriptor instead.
func (*RespArticleDetail) Descriptor() ([]byte, []int) {
	return file_blog_v1_article_proto_rawDescGZIP(), []int{5}
}

func (x *RespArticleDetail) GetDetail() *Article {
	if x != nil {
		return x.Detail
	}
	return nil
}

// 请求page页所有文章
type ReqListArticle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid  int32 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Page int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *ReqListArticle) Reset() {
	*x = ReqListArticle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_v1_article_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqListArticle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqListArticle) ProtoMessage() {}

func (x *ReqListArticle) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_article_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqListArticle.ProtoReflect.Descriptor instead.
func (*ReqListArticle) Descriptor() ([]byte, []int) {
	return file_blog_v1_article_proto_rawDescGZIP(), []int{6}
}

func (x *ReqListArticle) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ReqListArticle) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type SnapArticle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Like    int32  `protobuf:"varint,2,opt,name=like,proto3" json:"like,omitempty"`
	Views   int32  `protobuf:"varint,3,opt,name=views,proto3" json:"views,omitempty"`
	Account string `protobuf:"bytes,4,opt,name=account,proto3" json:"account,omitempty"`
	Title   string `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Intro   string `protobuf:"bytes,6,opt,name=intro,proto3" json:"intro,omitempty"`
}

func (x *SnapArticle) Reset() {
	*x = SnapArticle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_v1_article_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnapArticle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapArticle) ProtoMessage() {}

func (x *SnapArticle) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_article_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapArticle.ProtoReflect.Descriptor instead.
func (*SnapArticle) Descriptor() ([]byte, []int) {
	return file_blog_v1_article_proto_rawDescGZIP(), []int{7}
}

func (x *SnapArticle) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SnapArticle) GetLike() int32 {
	if x != nil {
		return x.Like
	}
	return 0
}

func (x *SnapArticle) GetViews() int32 {
	if x != nil {
		return x.Views
	}
	return 0
}

func (x *SnapArticle) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *SnapArticle) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SnapArticle) GetIntro() string {
	if x != nil {
		return x.Intro
	}
	return ""
}

type RespListArticle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Articles []*SnapArticle `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
}

func (x *RespListArticle) Reset() {
	*x = RespListArticle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_v1_article_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespListArticle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespListArticle) ProtoMessage() {}

func (x *RespListArticle) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_article_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespListArticle.ProtoReflect.Descriptor instead.
func (*RespListArticle) Descriptor() ([]byte, []int) {
	return file_blog_v1_article_proto_rawDescGZIP(), []int{8}
}

func (x *RespListArticle) GetArticles() []*SnapArticle {
	if x != nil {
		return x.Articles
	}
	return nil
}

// like文章
type ReqLikeArticle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ArticleId int32 `protobuf:"varint,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
}

func (x *ReqLikeArticle) Reset() {
	*x = ReqLikeArticle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_v1_article_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqLikeArticle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqLikeArticle) ProtoMessage() {}

func (x *ReqLikeArticle) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_article_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqLikeArticle.ProtoReflect.Descriptor instead.
func (*ReqLikeArticle) Descriptor() ([]byte, []int) {
	return file_blog_v1_article_proto_rawDescGZIP(), []int{9}
}

func (x *ReqLikeArticle) GetArticleId() int32 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

type RespLikeArticle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RespLikeArticle) Reset() {
	*x = RespLikeArticle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_v1_article_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespLikeArticle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespLikeArticle) ProtoMessage() {}

func (x *RespLikeArticle) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_article_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespLikeArticle.ProtoReflect.Descriptor instead.
func (*RespLikeArticle) Descriptor() ([]byte, []int) {
	return file_blog_v1_article_proto_rawDescGZIP(), []int{10}
}

// 浏览文章
type ReqHitsArticle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ArticleId int32 `protobuf:"varint,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
}

func (x *ReqHitsArticle) Reset() {
	*x = ReqHitsArticle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_v1_article_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqHitsArticle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqHitsArticle) ProtoMessage() {}

func (x *ReqHitsArticle) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_article_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqHitsArticle.ProtoReflect.Descriptor instead.
func (*ReqHitsArticle) Descriptor() ([]byte, []int) {
	return file_blog_v1_article_proto_rawDescGZIP(), []int{11}
}

func (x *ReqHitsArticle) GetArticleId() int32 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

type RespHitsArticle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RespHitsArticle) Reset() {
	*x = RespHitsArticle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_v1_article_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespHitsArticle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespHitsArticle) ProtoMessage() {}

func (x *RespHitsArticle) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_article_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespHitsArticle.ProtoReflect.Descriptor instead.
func (*RespHitsArticle) Descriptor() ([]byte, []int) {
	return file_blog_v1_article_proto_rawDescGZIP(), []int{12}
}

var File_blog_v1_article_proto protoreflect.FileDescriptor

var file_blog_v1_article_proto_rawDesc = []byte{
	0x0a, 0x15, 0x62, 0x6c, 0x6f, 0x67, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x76, 0x31, 0x1a, 0x16, 0x62, 0x6c, 0x6f, 0x67, 0x2f, 0x76, 0x31, 0x2f, 0x62, 0x6c,
	0x6f, 0x67, 0x5f, 0x64, 0x65, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x50, 0x0a, 0x0e,
	0x52, 0x65, 0x71, 0x53, 0x61, 0x76, 0x65, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x75, 0x69, 0x64,
	0x12, 0x2c, 0x0a, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x41,
	0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x22, 0x2c,
	0x0a, 0x0f, 0x52, 0x65, 0x73, 0x70, 0x53, 0x61, 0x76, 0x65, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c,
	0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x43, 0x0a, 0x10,
	0x52, 0x65, 0x71, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x75,
	0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x49,
	0x64, 0x22, 0x2e, 0x0a, 0x11, 0x52, 0x65, 0x73, 0x70, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41,
	0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64,
	0x65, 0x22, 0x43, 0x0a, 0x10, 0x52, 0x65, 0x71, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x72, 0x74, 0x69, 0x63,
	0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x61, 0x72, 0x74,
	0x69, 0x63, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x41, 0x0a, 0x11, 0x52, 0x65, 0x73, 0x70, 0x41, 0x72,
	0x74, 0x69, 0x63, 0x6c, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x2c, 0x0a, 0x06, 0x64,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x62, 0x6c,
	0x6f, 0x67, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c,
	0x65, 0x52, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x22, 0x36, 0x0a, 0x0e, 0x52, 0x65, 0x71,
	0x4c, 0x69, 0x73, 0x74, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x22, 0x8d, 0x01, 0x0a, 0x0b, 0x53, 0x6e, 0x61, 0x70, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6b, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x6c, 0x69, 0x6b, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x69, 0x65, 0x77, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x69, 0x65, 0x77, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69,
	0x6e, 0x74, 0x72, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6e, 0x74, 0x72,
	0x6f, 0x22, 0x47, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x72, 0x74,
	0x69, 0x63, 0x6c, 0x65, 0x12, 0x34, 0x0a, 0x08, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x6e, 0x61, 0x70, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65,
	0x52, 0x08, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x73, 0x22, 0x2f, 0x0a, 0x0e, 0x52, 0x65,
	0x71, 0x4c, 0x69, 0x6b, 0x65, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x12, 0x1d, 0x0a, 0x0a,
	0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x09, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x11, 0x0a, 0x0f, 0x52,
	0x65, 0x73, 0x70, 0x4c, 0x69, 0x6b, 0x65, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x22, 0x2f,
	0x0a, 0x0e, 0x52, 0x65, 0x71, 0x48, 0x69, 0x74, 0x73, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x49, 0x64, 0x22,
	0x11, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x70, 0x48, 0x69, 0x74, 0x73, 0x41, 0x72, 0x74, 0x69, 0x63,
	0x6c, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x62, 0x6c, 0x6f, 0x67, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_blog_v1_article_proto_rawDescOnce sync.Once
	file_blog_v1_article_proto_rawDescData = file_blog_v1_article_proto_rawDesc
)

func file_blog_v1_article_proto_rawDescGZIP() []byte {
	file_blog_v1_article_proto_rawDescOnce.Do(func() {
		file_blog_v1_article_proto_rawDescData = protoimpl.X.CompressGZIP(file_blog_v1_article_proto_rawDescData)
	})
	return file_blog_v1_article_proto_rawDescData
}

var file_blog_v1_article_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_blog_v1_article_proto_goTypes = []interface{}{
	(*ReqSaveArticle)(nil),    // 0: blog.api.v1.ReqSaveArticle
	(*RespSaveArticle)(nil),   // 1: blog.api.v1.RespSaveArticle
	(*ReqDeleteArticle)(nil),  // 2: blog.api.v1.ReqDeleteArticle
	(*RespDeleteArticle)(nil), // 3: blog.api.v1.RespDeleteArticle
	(*ReqArticleDetail)(nil),  // 4: blog.api.v1.ReqArticleDetail
	(*RespArticleDetail)(nil), // 5: blog.api.v1.RespArticleDetail
	(*ReqListArticle)(nil),    // 6: blog.api.v1.ReqListArticle
	(*SnapArticle)(nil),       // 7: blog.api.v1.SnapArticle
	(*RespListArticle)(nil),   // 8: blog.api.v1.RespListArticle
	(*ReqLikeArticle)(nil),    // 9: blog.api.v1.ReqLikeArticle
	(*RespLikeArticle)(nil),   // 10: blog.api.v1.RespLikeArticle
	(*ReqHitsArticle)(nil),    // 11: blog.api.v1.ReqHitsArticle
	(*RespHitsArticle)(nil),   // 12: blog.api.v1.RespHitsArticle
	(*Article)(nil),           // 13: blog.api.v1.Article
}
var file_blog_v1_article_proto_depIdxs = []int32{
	13, // 0: blog.api.v1.ReqSaveArticle.detail:type_name -> blog.api.v1.Article
	13, // 1: blog.api.v1.RespArticleDetail.detail:type_name -> blog.api.v1.Article
	7,  // 2: blog.api.v1.RespListArticle.articles:type_name -> blog.api.v1.SnapArticle
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_blog_v1_article_proto_init() }
func file_blog_v1_article_proto_init() {
	if File_blog_v1_article_proto != nil {
		return
	}
	file_blog_v1_blog_def_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_blog_v1_article_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSaveArticle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_v1_article_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespSaveArticle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_v1_article_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqDeleteArticle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_v1_article_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespDeleteArticle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_v1_article_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqArticleDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_v1_article_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespArticleDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_v1_article_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqListArticle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_v1_article_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SnapArticle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_v1_article_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespListArticle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_v1_article_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqLikeArticle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_v1_article_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespLikeArticle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_v1_article_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqHitsArticle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_v1_article_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespHitsArticle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_blog_v1_article_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blog_v1_article_proto_goTypes,
		DependencyIndexes: file_blog_v1_article_proto_depIdxs,
		MessageInfos:      file_blog_v1_article_proto_msgTypes,
	}.Build()
	File_blog_v1_article_proto = out.File
	file_blog_v1_article_proto_rawDesc = nil
	file_blog_v1_article_proto_goTypes = nil
	file_blog_v1_article_proto_depIdxs = nil
}
