// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.1
// source: chatproxy/v1/chatproxy.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 给ChatGPT的文本
type ChatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chatproxy_v1_chatproxy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatproxy_v1_chatproxy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_chatproxy_v1_chatproxy_proto_rawDescGZIP(), []int{0}
}

func (x *ChatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ChatGPT回应的文本
type ChatReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ChatReply) Reset() {
	*x = ChatReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chatproxy_v1_chatproxy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatReply) ProtoMessage() {}

func (x *ChatReply) ProtoReflect() protoreflect.Message {
	mi := &file_chatproxy_v1_chatproxy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatReply.ProtoReflect.Descriptor instead.
func (*ChatReply) Descriptor() ([]byte, []int) {
	return file_chatproxy_v1_chatproxy_proto_rawDescGZIP(), []int{1}
}

func (x *ChatReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ws聊天内容
type WsChatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Message   string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *WsChatRequest) Reset() {
	*x = WsChatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chatproxy_v1_chatproxy_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WsChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WsChatRequest) ProtoMessage() {}

func (x *WsChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatproxy_v1_chatproxy_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WsChatRequest.ProtoReflect.Descriptor instead.
func (*WsChatRequest) Descriptor() ([]byte, []int) {
	return file_chatproxy_v1_chatproxy_proto_rawDescGZIP(), []int{2}
}

func (x *WsChatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *WsChatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ws聊天回应
type WsChatReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
}

func (x *WsChatReply) Reset() {
	*x = WsChatReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chatproxy_v1_chatproxy_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WsChatReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WsChatReply) ProtoMessage() {}

func (x *WsChatReply) ProtoReflect() protoreflect.Message {
	mi := &file_chatproxy_v1_chatproxy_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WsChatReply.ProtoReflect.Descriptor instead.
func (*WsChatReply) Descriptor() ([]byte, []int) {
	return file_chatproxy_v1_chatproxy_proto_rawDescGZIP(), []int{3}
}

func (x *WsChatReply) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// ws聊天同步
type NtfWsChatMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Message   string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *NtfWsChatMsg) Reset() {
	*x = NtfWsChatMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chatproxy_v1_chatproxy_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NtfWsChatMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NtfWsChatMsg) ProtoMessage() {}

func (x *NtfWsChatMsg) ProtoReflect() protoreflect.Message {
	mi := &file_chatproxy_v1_chatproxy_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NtfWsChatMsg.ProtoReflect.Descriptor instead.
func (*NtfWsChatMsg) Descriptor() ([]byte, []int) {
	return file_chatproxy_v1_chatproxy_proto_rawDescGZIP(), []int{4}
}

func (x *NtfWsChatMsg) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *NtfWsChatMsg) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_chatproxy_v1_chatproxy_proto protoreflect.FileDescriptor

var file_chatproxy_v1_chatproxy_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x63, 0x68, 0x61, 0x74, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2f, 0x76, 0x31, 0x2f, 0x63,
	0x68, 0x61, 0x74, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c,
	0x63, 0x68, 0x61, 0x74, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x27, 0x0a, 0x0b, 0x43, 0x68,
	0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x22, 0x25, 0x0a, 0x09, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x48, 0x0a, 0x0d, 0x57, 0x73,
	0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0x2c, 0x0a, 0x0b, 0x57, 0x73, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x49, 0x64, 0x22, 0x47, 0x0a, 0x0c, 0x4e, 0x74, 0x66, 0x57, 0x73, 0x43, 0x68, 0x61, 0x74, 0x4d,
	0x73, 0x67, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xae, 0x01, 0x0a, 0x09,
	0x43, 0x68, 0x61, 0x74, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x12, 0x57, 0x0a, 0x0a, 0x53, 0x61, 0x79,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x19, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x70, 0x72,
	0x6f, 0x78, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x17, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x15, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x0f, 0x3a, 0x01, 0x2a, 0x22, 0x0a, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x70, 0x72, 0x6f,
	0x78, 0x79, 0x12, 0x48, 0x0a, 0x0c, 0x57, 0x73, 0x53, 0x61, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x1b, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x76,
	0x31, 0x2e, 0x57, 0x73, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x19, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x57,
	0x73, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x11, 0x5a, 0x0f,
	0x63, 0x68, 0x61, 0x74, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_chatproxy_v1_chatproxy_proto_rawDescOnce sync.Once
	file_chatproxy_v1_chatproxy_proto_rawDescData = file_chatproxy_v1_chatproxy_proto_rawDesc
)

func file_chatproxy_v1_chatproxy_proto_rawDescGZIP() []byte {
	file_chatproxy_v1_chatproxy_proto_rawDescOnce.Do(func() {
		file_chatproxy_v1_chatproxy_proto_rawDescData = protoimpl.X.CompressGZIP(file_chatproxy_v1_chatproxy_proto_rawDescData)
	})
	return file_chatproxy_v1_chatproxy_proto_rawDescData
}

var file_chatproxy_v1_chatproxy_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_chatproxy_v1_chatproxy_proto_goTypes = []interface{}{
	(*ChatRequest)(nil),   // 0: chatproxy.v1.ChatRequest
	(*ChatReply)(nil),     // 1: chatproxy.v1.ChatReply
	(*WsChatRequest)(nil), // 2: chatproxy.v1.WsChatRequest
	(*WsChatReply)(nil),   // 3: chatproxy.v1.WsChatReply
	(*NtfWsChatMsg)(nil),  // 4: chatproxy.v1.NtfWsChatMsg
}
var file_chatproxy_v1_chatproxy_proto_depIdxs = []int32{
	0, // 0: chatproxy.v1.ChatProxy.SayMessage:input_type -> chatproxy.v1.ChatRequest
	2, // 1: chatproxy.v1.ChatProxy.WsSayMessage:input_type -> chatproxy.v1.WsChatRequest
	1, // 2: chatproxy.v1.ChatProxy.SayMessage:output_type -> chatproxy.v1.ChatReply
	3, // 3: chatproxy.v1.ChatProxy.WsSayMessage:output_type -> chatproxy.v1.WsChatReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_chatproxy_v1_chatproxy_proto_init() }
func file_chatproxy_v1_chatproxy_proto_init() {
	if File_chatproxy_v1_chatproxy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_chatproxy_v1_chatproxy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chatproxy_v1_chatproxy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chatproxy_v1_chatproxy_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WsChatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chatproxy_v1_chatproxy_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WsChatReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chatproxy_v1_chatproxy_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NtfWsChatMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chatproxy_v1_chatproxy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chatproxy_v1_chatproxy_proto_goTypes,
		DependencyIndexes: file_chatproxy_v1_chatproxy_proto_depIdxs,
		MessageInfos:      file_chatproxy_v1_chatproxy_proto_msgTypes,
	}.Build()
	File_chatproxy_v1_chatproxy_proto = out.File
	file_chatproxy_v1_chatproxy_proto_rawDesc = nil
	file_chatproxy_v1_chatproxy_proto_goTypes = nil
	file_chatproxy_v1_chatproxy_proto_depIdxs = nil
}
