// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.1
// source: nuwa/v1/nuwa.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReqUserLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid     int32  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Account string `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Sign    string `protobuf:"bytes,3,opt,name=sign,proto3" json:"sign,omitempty"`
}

func (x *ReqUserLogin) Reset() {
	*x = ReqUserLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nuwa_v1_nuwa_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqUserLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqUserLogin) ProtoMessage() {}

func (x *ReqUserLogin) ProtoReflect() protoreflect.Message {
	mi := &file_nuwa_v1_nuwa_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqUserLogin.ProtoReflect.Descriptor instead.
func (*ReqUserLogin) Descriptor() ([]byte, []int) {
	return file_nuwa_v1_nuwa_proto_rawDescGZIP(), []int{0}
}

func (x *ReqUserLogin) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ReqUserLogin) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *ReqUserLogin) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

type RespUserLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode int32 `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
}

func (x *RespUserLogin) Reset() {
	*x = RespUserLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nuwa_v1_nuwa_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespUserLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespUserLogin) ProtoMessage() {}

func (x *RespUserLogin) ProtoReflect() protoreflect.Message {
	mi := &file_nuwa_v1_nuwa_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespUserLogin.ProtoReflect.Descriptor instead.
func (*RespUserLogin) Descriptor() ([]byte, []int) {
	return file_nuwa_v1_nuwa_proto_rawDescGZIP(), []int{1}
}

func (x *RespUserLogin) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

type ReqUserLogout struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid int32 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *ReqUserLogout) Reset() {
	*x = ReqUserLogout{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nuwa_v1_nuwa_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqUserLogout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqUserLogout) ProtoMessage() {}

func (x *ReqUserLogout) ProtoReflect() protoreflect.Message {
	mi := &file_nuwa_v1_nuwa_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqUserLogout.ProtoReflect.Descriptor instead.
func (*ReqUserLogout) Descriptor() ([]byte, []int) {
	return file_nuwa_v1_nuwa_proto_rawDescGZIP(), []int{2}
}

func (x *ReqUserLogout) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type RespUserLogout struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode int32 `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
}

func (x *RespUserLogout) Reset() {
	*x = RespUserLogout{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nuwa_v1_nuwa_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespUserLogout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespUserLogout) ProtoMessage() {}

func (x *RespUserLogout) ProtoReflect() protoreflect.Message {
	mi := &file_nuwa_v1_nuwa_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespUserLogout.ProtoReflect.Descriptor instead.
func (*RespUserLogout) Descriptor() ([]byte, []int) {
	return file_nuwa_v1_nuwa_proto_rawDescGZIP(), []int{3}
}

func (x *RespUserLogout) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

type ReqUserSession struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid   int32  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Token string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *ReqUserSession) Reset() {
	*x = ReqUserSession{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nuwa_v1_nuwa_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqUserSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqUserSession) ProtoMessage() {}

func (x *ReqUserSession) ProtoReflect() protoreflect.Message {
	mi := &file_nuwa_v1_nuwa_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqUserSession.ProtoReflect.Descriptor instead.
func (*ReqUserSession) Descriptor() ([]byte, []int) {
	return file_nuwa_v1_nuwa_proto_rawDescGZIP(), []int{4}
}

func (x *ReqUserSession) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ReqUserSession) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RespUserSession struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode int32  `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	User    *CUser `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *RespUserSession) Reset() {
	*x = RespUserSession{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nuwa_v1_nuwa_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespUserSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespUserSession) ProtoMessage() {}

func (x *RespUserSession) ProtoReflect() protoreflect.Message {
	mi := &file_nuwa_v1_nuwa_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespUserSession.ProtoReflect.Descriptor instead.
func (*RespUserSession) Descriptor() ([]byte, []int) {
	return file_nuwa_v1_nuwa_proto_rawDescGZIP(), []int{5}
}

func (x *RespUserSession) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *RespUserSession) GetUser() *CUser {
	if x != nil {
		return x.User
	}
	return nil
}

type CUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid       int32  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Sex       int32  `protobuf:"varint,2,opt,name=sex,proto3" json:"sex,omitempty"`
	Account   string `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	Nickname  string `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Intro     string `protobuf:"bytes,5,opt,name=intro,proto3" json:"intro,omitempty"`
	Indexlink string `protobuf:"bytes,6,opt,name=indexlink,proto3" json:"indexlink,omitempty"`
	Session   string `protobuf:"bytes,7,opt,name=session,proto3" json:"session,omitempty"`
	State     int32  `protobuf:"varint,8,opt,name=state,proto3" json:"state,omitempty"`
	Phone     string `protobuf:"bytes,9,opt,name=phone,proto3" json:"phone,omitempty"`
}

func (x *CUser) Reset() {
	*x = CUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nuwa_v1_nuwa_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CUser) ProtoMessage() {}

func (x *CUser) ProtoReflect() protoreflect.Message {
	mi := &file_nuwa_v1_nuwa_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CUser.ProtoReflect.Descriptor instead.
func (*CUser) Descriptor() ([]byte, []int) {
	return file_nuwa_v1_nuwa_proto_rawDescGZIP(), []int{6}
}

func (x *CUser) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CUser) GetSex() int32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *CUser) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *CUser) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *CUser) GetIntro() string {
	if x != nil {
		return x.Intro
	}
	return ""
}

func (x *CUser) GetIndexlink() string {
	if x != nil {
		return x.Indexlink
	}
	return ""
}

func (x *CUser) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *CUser) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *CUser) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

var File_nuwa_v1_nuwa_proto protoreflect.FileDescriptor

var file_nuwa_v1_nuwa_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6e, 0x75, 0x77, 0x61, 0x2f, 0x76, 0x31, 0x2f, 0x6e, 0x75, 0x77, 0x61, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x6e, 0x75, 0x77, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76,
	0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e,
	0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x4e, 0x0a, 0x0c, 0x52, 0x65, 0x71, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x75, 0x69,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x69, 0x67, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x22,
	0x2a, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x70, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x12, 0x19, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x21, 0x0a, 0x0d, 0x52,
	0x65, 0x71, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x2b,
	0x0a, 0x0e, 0x52, 0x65, 0x73, 0x70, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74,
	0x12, 0x19, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x38, 0x0a, 0x0e, 0x52,
	0x65, 0x71, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x54, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x70, 0x55, 0x73, 0x65,
	0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x72, 0x72, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x6e, 0x75, 0x77, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0xdb, 0x01, 0x0a, 0x05,
	0x43, 0x55, 0x73, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x78, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x65, 0x78, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x69, 0x6e, 0x74, 0x72, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x69, 0x6e, 0x74, 0x72, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x6c, 0x69,
	0x6e, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x6c,
	0x69, 0x6e, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x32, 0x99, 0x02, 0x0a, 0x0b, 0x4e, 0x75,
	0x77, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x51, 0x0a, 0x05, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x12, 0x19, 0x2e, 0x6e, 0x75, 0x77, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31,
	0x2e, 0x52, 0x65, 0x71, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x1a, 0x1a, 0x2e,
	0x6e, 0x75, 0x77, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x22, 0x11, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x0b, 0x3a, 0x01, 0x2a, 0x22, 0x06, 0x2f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x55, 0x0a, 0x06,
	0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x12, 0x1a, 0x2e, 0x6e, 0x75, 0x77, 0x61, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x71, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x6f,
	0x75, 0x74, 0x1a, 0x1b, 0x2e, 0x6e, 0x75, 0x77, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x22,
	0x12, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0c, 0x3a, 0x01, 0x2a, 0x22, 0x07, 0x2f, 0x6c, 0x6f, 0x67,
	0x6f, 0x75, 0x74, 0x12, 0x60, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x2e, 0x6e, 0x75, 0x77, 0x61, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x71, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x1a, 0x1c, 0x2e, 0x6e, 0x75, 0x77, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x22, 0x13, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0d, 0x3a, 0x01, 0x2a, 0x22, 0x08, 0x2f, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x0c, 0x5a, 0x0a, 0x6e, 0x75, 0x77, 0x61, 0x2f, 0x76, 0x31,
	0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_nuwa_v1_nuwa_proto_rawDescOnce sync.Once
	file_nuwa_v1_nuwa_proto_rawDescData = file_nuwa_v1_nuwa_proto_rawDesc
)

func file_nuwa_v1_nuwa_proto_rawDescGZIP() []byte {
	file_nuwa_v1_nuwa_proto_rawDescOnce.Do(func() {
		file_nuwa_v1_nuwa_proto_rawDescData = protoimpl.X.CompressGZIP(file_nuwa_v1_nuwa_proto_rawDescData)
	})
	return file_nuwa_v1_nuwa_proto_rawDescData
}

var file_nuwa_v1_nuwa_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_nuwa_v1_nuwa_proto_goTypes = []interface{}{
	(*ReqUserLogin)(nil),    // 0: nuwa.api.v1.ReqUserLogin
	(*RespUserLogin)(nil),   // 1: nuwa.api.v1.RespUserLogin
	(*ReqUserLogout)(nil),   // 2: nuwa.api.v1.ReqUserLogout
	(*RespUserLogout)(nil),  // 3: nuwa.api.v1.RespUserLogout
	(*ReqUserSession)(nil),  // 4: nuwa.api.v1.ReqUserSession
	(*RespUserSession)(nil), // 5: nuwa.api.v1.RespUserSession
	(*CUser)(nil),           // 6: nuwa.api.v1.CUser
}
var file_nuwa_v1_nuwa_proto_depIdxs = []int32{
	6, // 0: nuwa.api.v1.RespUserSession.user:type_name -> nuwa.api.v1.CUser
	0, // 1: nuwa.api.v1.NuwaService.Login:input_type -> nuwa.api.v1.ReqUserLogin
	2, // 2: nuwa.api.v1.NuwaService.Logout:input_type -> nuwa.api.v1.ReqUserLogout
	4, // 3: nuwa.api.v1.NuwaService.GetUserSession:input_type -> nuwa.api.v1.ReqUserSession
	1, // 4: nuwa.api.v1.NuwaService.Login:output_type -> nuwa.api.v1.RespUserLogin
	3, // 5: nuwa.api.v1.NuwaService.Logout:output_type -> nuwa.api.v1.RespUserLogout
	5, // 6: nuwa.api.v1.NuwaService.GetUserSession:output_type -> nuwa.api.v1.RespUserSession
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_nuwa_v1_nuwa_proto_init() }
func file_nuwa_v1_nuwa_proto_init() {
	if File_nuwa_v1_nuwa_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_nuwa_v1_nuwa_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqUserLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nuwa_v1_nuwa_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespUserLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nuwa_v1_nuwa_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqUserLogout); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nuwa_v1_nuwa_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespUserLogout); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nuwa_v1_nuwa_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqUserSession); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nuwa_v1_nuwa_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespUserSession); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nuwa_v1_nuwa_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nuwa_v1_nuwa_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nuwa_v1_nuwa_proto_goTypes,
		DependencyIndexes: file_nuwa_v1_nuwa_proto_depIdxs,
		MessageInfos:      file_nuwa_v1_nuwa_proto_msgTypes,
	}.Build()
	File_nuwa_v1_nuwa_proto = out.File
	file_nuwa_v1_nuwa_proto_rawDesc = nil
	file_nuwa_v1_nuwa_proto_goTypes = nil
	file_nuwa_v1_nuwa_proto_depIdxs = nil
}
