// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: nuwa/v1/nuwa.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NuwaClient is the client API for Nuwa service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NuwaClient interface {
	// 获取后台首页
	GetIndex(ctx context.Context, in *BackEndIndexReq, opts ...grpc.CallOption) (*BackEndIndexResp, error)
}

type nuwaClient struct {
	cc grpc.ClientConnInterface
}

func NewNuwaClient(cc grpc.ClientConnInterface) NuwaClient {
	return &nuwaClient{cc}
}

func (c *nuwaClient) GetIndex(ctx context.Context, in *BackEndIndexReq, opts ...grpc.CallOption) (*BackEndIndexResp, error) {
	out := new(BackEndIndexResp)
	err := c.cc.Invoke(ctx, "/api.nuwa.v1.Nuwa/GetIndex", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NuwaServer is the server API for Nuwa service.
// All implementations must embed UnimplementedNuwaServer
// for forward compatibility
type NuwaServer interface {
	// 获取后台首页
	GetIndex(context.Context, *BackEndIndexReq) (*BackEndIndexResp, error)
	mustEmbedUnimplementedNuwaServer()
}

// UnimplementedNuwaServer must be embedded to have forward compatible implementations.
type UnimplementedNuwaServer struct {
}

func (UnimplementedNuwaServer) GetIndex(context.Context, *BackEndIndexReq) (*BackEndIndexResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIndex not implemented")
}
func (UnimplementedNuwaServer) mustEmbedUnimplementedNuwaServer() {}

// UnsafeNuwaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NuwaServer will
// result in compilation errors.
type UnsafeNuwaServer interface {
	mustEmbedUnimplementedNuwaServer()
}

func RegisterNuwaServer(s grpc.ServiceRegistrar, srv NuwaServer) {
	s.RegisterService(&Nuwa_ServiceDesc, srv)
}

func _Nuwa_GetIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackEndIndexReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NuwaServer).GetIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.nuwa.v1.Nuwa/GetIndex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NuwaServer).GetIndex(ctx, req.(*BackEndIndexReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Nuwa_ServiceDesc is the grpc.ServiceDesc for Nuwa service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Nuwa_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.nuwa.v1.Nuwa",
	HandlerType: (*NuwaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetIndex",
			Handler:    _Nuwa_GetIndex_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nuwa/v1/nuwa.proto",
}
